name: CI Pipeline

on:
  push:
    branches:
      - master  # Trigger on push to the main branch
  pull_request:
    branches:
      - master  # Trigger on PR targeting the main branch

jobs:
  # Job for running unit tests
  run-tests:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'  # Set the Java version (adjust based on your project)
          distribution: 'temurin'

      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw
        
      - name: Install dependencies
        run: ./mvnw install  # Ensure tests are not skipped

      - name: Run unit tests
        run: ./mvnw clean test -Dtest=project.unit.*.*Test # Run all unit tests in the "project.unit" package

      - name: Run integration tests
        run: ./mvnw clean test -Dtest=project.integration.*Test  # Run all integration tests in the "project.integration" package

 
